// Generated by backend-go/cmd/gen-rules — do not edit by hand.
// Regenerate with: (cd backend-go && go run ./cmd/gen-rules)

export interface PLRule {
	readonly key: string;
	readonly name: string;
	readonly category: string;
	readonly value: number;
	readonly unit: string;
	readonly year: number;
	readonly effectiveDate: string;
	readonly sourceURL: string;
	readonly lastCheckedDate: string;
	readonly description: string;
}

export const PL_RULES = {
	ike_limit_2026: {
		key: 'ike_limit_2026',
		name: 'Roczny limit wpłat IKE',
		category: 'ike_limit',
		value: 28260,
		unit: 'PLN',
		year: 2026,
		effectiveDate: '2026-01-01',
		sourceURL: 'https://www.gov.pl/web/finanse/limity-wplat-na-ike-i-ikze',
		lastCheckedDate: '2026-05-24',
		description: 'Maksymalna roczna wpłata na konto IKE w 2026 r.'
	},
	ikze_limit_2026: {
		key: 'ikze_limit_2026',
		name: 'Roczny limit wpłat IKZE',
		category: 'ikze_limit',
		value: 11304,
		unit: 'PLN',
		year: 2026,
		effectiveDate: '2026-01-01',
		sourceURL: 'https://www.gov.pl/web/finanse/limity-wplat-na-ike-i-ikze',
		lastCheckedDate: '2026-05-24',
		description: 'Maksymalna roczna wpłata na konto IKZE w 2026 r.'
	},
	ikze_limit_b2b_2026: {
		key: 'ikze_limit_b2b_2026',
		name: 'Roczny limit IKZE (samozatrudnieni)',
		category: 'ikze_limit',
		value: 16956,
		unit: 'PLN',
		year: 2026,
		effectiveDate: '2026-01-01',
		sourceURL: 'https://www.gov.pl/web/finanse/limity-wplat-na-ike-i-ikze',
		lastCheckedDate: '2026-05-24',
		description: 'Podwyższony limit dla osób prowadzących pozarolniczą działalność gospodarczą.'
	},
	ppk_below_threshold_2026: {
		key: 'ppk_below_threshold_2026',
		name: 'Próg wynagrodzenia PPK (1,2× minimalnej krajowej)',
		category: 'ppk',
		value: 5767,
		unit: 'PLN/miesiąc',
		year: 2026,
		effectiveDate: '2026-01-01',
		sourceURL: 'https://www.mojeppk.pl/',
		lastCheckedDate: '2026-05-24',
		description: 'Pracownik zarabiający poniżej tego progu może obniżyć składkę pracownika z 2% do 0,5%.'
	},
	minimum_wage_2026: {
		key: 'minimum_wage_2026',
		name: 'Płaca minimalna brutto',
		category: 'minimum_wage',
		value: 4806,
		unit: 'PLN/miesiąc',
		year: 2026,
		effectiveDate: '2026-01-01',
		sourceURL: 'https://www.gov.pl/web/rodzina/place-minimalna',
		lastCheckedDate: '2026-05-24',
		description: 'Minimalne wynagrodzenie obowiązujące w 2026 r.'
	},
	pit_threshold_first_2026: {
		key: 'pit_threshold_first_2026',
		name: 'Próg pierwszego progu PIT',
		category: 'pit',
		value: 120000,
		unit: 'PLN',
		year: 2026,
		effectiveDate: '2026-01-01',
		sourceURL: 'https://www.podatki.gov.pl/pit/abc-pit/skala-podatkowa/',
		lastCheckedDate: '2026-05-24',
		description: 'Dochód, po przekroczeniu którego stosuje się drugi próg skali PIT.'
	},
	pit_rate_first_2026: {
		key: 'pit_rate_first_2026',
		name: 'Stawka PIT — pierwszy próg',
		category: 'pit',
		value: 0.12,
		unit: 'udział',
		year: 2026,
		effectiveDate: '2026-01-01',
		sourceURL: 'https://www.podatki.gov.pl/pit/abc-pit/skala-podatkowa/',
		lastCheckedDate: '2026-05-24',
		description: 'Skala podatkowa: 12% do progu, pomniejszone o kwotę wolną.'
	},
	pit_rate_second_2026: {
		key: 'pit_rate_second_2026',
		name: 'Stawka PIT — drugi próg',
		category: 'pit',
		value: 0.32,
		unit: 'udział',
		year: 2026,
		effectiveDate: '2026-01-01',
		sourceURL: 'https://www.podatki.gov.pl/pit/abc-pit/skala-podatkowa/',
		lastCheckedDate: '2026-05-24',
		description: 'Stawka stosowana do dochodu powyżej pierwszego progu.'
	},
	capital_gains_tax_2026: {
		key: 'capital_gains_tax_2026',
		name: 'Podatek Belki (od zysków kapitałowych)',
		category: 'capital_gains',
		value: 0.19,
		unit: 'udział',
		year: 2026,
		effectiveDate: '2026-01-01',
		sourceURL: 'https://www.podatki.gov.pl/pit/abc-pit/podatki-od-zyskow-kapitalowych/',
		lastCheckedDate: '2026-05-24',
		description: 'Zryczałtowany podatek od zysków z inwestycji (oszczędności, akcje, fundusze).'
	},
	pit_free_amount_2026: {
		key: 'pit_free_amount_2026',
		name: 'Kwota wolna od podatku PIT',
		category: 'pit',
		value: 30000,
		unit: 'PLN',
		year: 2026,
		effectiveDate: '2026-01-01',
		sourceURL: 'https://www.podatki.gov.pl/pit/abc-pit/skala-podatkowa/',
		lastCheckedDate: '2026-05-24',
		description: 'Roczny dochód wolny od podatku w skali PIT.'
	},
	pit_solidarity_threshold_2026: {
		key: 'pit_solidarity_threshold_2026',
		name: 'Próg daniny solidarnościowej',
		category: 'pit',
		value: 1000000,
		unit: 'PLN',
		year: 2026,
		effectiveDate: '2026-01-01',
		sourceURL: 'https://www.podatki.gov.pl/pit/abc-pit/danina-solidarnosciowa/',
		lastCheckedDate: '2026-05-24',
		description: 'Roczny dochód, powyżej którego doliczana jest danina solidarnościowa.'
	},
	pit_solidarity_rate_2026: {
		key: 'pit_solidarity_rate_2026',
		name: 'Stawka daniny solidarnościowej',
		category: 'pit',
		value: 0.04,
		unit: 'udział',
		year: 2026,
		effectiveDate: '2026-01-01',
		sourceURL: 'https://www.podatki.gov.pl/pit/abc-pit/danina-solidarnosciowa/',
		lastCheckedDate: '2026-05-24',
		description: 'Dodatkowe 4% od nadwyżki dochodu ponad 1 mln PLN.'
	},
	zus_cap_30x_2026: {
		key: 'zus_cap_30x_2026',
		name: 'Limit 30-krotności (podstawa ZUS)',
		category: 'zus',
		value: 282600,
		unit: 'PLN',
		year: 2026,
		effectiveDate: '2026-01-01',
		sourceURL: 'https://www.zus.pl/baza-wiedzy/skladki-wskazniki-odsetki/skladki/wysokosc-skladek-na-ubezpieczenia-spoleczne',
		lastCheckedDate: '2026-05-24',
		description: 'Roczna podstawa wymiaru składek emerytalnych i rentowych — przyjmowane 30× prognozowane przeciętne wynagrodzenie.'
	},
	b2b_liniowy_rate_2026: {
		key: 'b2b_liniowy_rate_2026',
		name: 'PIT liniowy B2B',
		category: 'pit',
		value: 0.19,
		unit: 'udział',
		year: 2026,
		effectiveDate: '2026-01-01',
		sourceURL: 'https://www.podatki.gov.pl/pit/abc-pit/zasady-opodatkowania/',
		lastCheckedDate: '2026-05-24',
		description: 'Liniowa stawka 19% dla osób prowadzących pozarolniczą działalność gospodarczą.'
	},
	ryczalt_it_rate_2026: {
		key: 'ryczalt_it_rate_2026',
		name: 'Ryczałt IT (12%)',
		category: 'pit',
		value: 0.12,
		unit: 'udział',
		year: 2026,
		effectiveDate: '2026-01-01',
		sourceURL: 'https://www.podatki.gov.pl/pit/abc-pit/zryczaltowane-formy-opodatkowania/ryczalt-od-przychodow-ewidencjonowanych/',
		lastCheckedDate: '2026-05-24',
		description: 'Stawka ryczałtu od przychodów ewidencjonowanych dla branży IT (PKWiU 62.0x).'
	}
} as const satisfies Record<string, PLRule>;
