"""Baseline schema generated from current SQLAlchemy models.

Creates the full finance-buddy schema as it stood when Alembic was adopted.
The schema is derived directly from ``Base.metadata`` (the model definitions),
so it always matches the ORM. Subsequent changes get their own autogenerated
revisions.

Revision ID: 0001
Revises:
Create Date: 2026-05-16

"""

from collections.abc import Sequence

from alembic import op
from app.core.database import Base

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
