// Command gen-rules emits a typed TypeScript view of the Polish-constants
// rules table so the frontend can read the same canonical values the
// backend uses without an HTTP round-trip per page load.
//
// Output: src/lib/utils/pl_rules.generated.ts. CI re-runs the command and
// fails on drift, the same way it does for openapi-go.json.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/Automaat/finance-buddy/backend-go/internal/rules"
)

const header = `// Generated by backend-go/cmd/gen-rules — do not edit by hand.
// Regenerate with: (cd backend-go && go run ./cmd/gen-rules)

`

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "gen-rules:", err)
		os.Exit(1)
	}
}

func run() error {
	out, err := outputPath()
	if err != nil {
		return err
	}
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("export interface PLRule {\n")
	b.WriteString("\treadonly key: string;\n")
	b.WriteString("\treadonly name: string;\n")
	b.WriteString("\treadonly category: string;\n")
	b.WriteString("\treadonly value: number;\n")
	b.WriteString("\treadonly unit: string;\n")
	b.WriteString("\treadonly year: number;\n")
	b.WriteString("\treadonly effectiveDate: string;\n")
	b.WriteString("\treadonly sourceURL: string;\n")
	b.WriteString("\treadonly lastCheckedDate: string;\n")
	b.WriteString("\treadonly description: string;\n")
	b.WriteString("}\n\n")
	// trailingComma: "none" in prettier config — emit fields joined by ",\n"
	// with no trailing comma on the last entry of either object or outer map.
	b.WriteString("export const PL_RULES = {\n")
	for i, r := range rules.Polish2026 {
		fields := []string{
			fmt.Sprintf("\t\tkey: %s", tsString(r.Key)),
			fmt.Sprintf("\t\tname: %s", tsString(r.Name)),
			fmt.Sprintf("\t\tcategory: %s", tsString(r.Category)),
			fmt.Sprintf("\t\tvalue: %s", r.Value.String()),
			fmt.Sprintf("\t\tunit: %s", tsString(r.Unit)),
			fmt.Sprintf("\t\tyear: %d", r.Year),
			fmt.Sprintf("\t\teffectiveDate: %s", tsString(r.EffectiveDate.Format("2006-01-02"))),
			fmt.Sprintf("\t\tsourceURL: %s", tsString(r.SourceURL)),
			fmt.Sprintf("\t\tlastCheckedDate: %s", tsString(r.LastCheckedDate.Format("2006-01-02"))),
			fmt.Sprintf("\t\tdescription: %s", tsString(r.Description)),
		}
		b.WriteString(fmt.Sprintf("\t%s: {\n", r.Key))
		b.WriteString(strings.Join(fields, ",\n"))
		b.WriteString("\n\t}")
		if i < len(rules.Polish2026)-1 {
			b.WriteString(",")
		}
		b.WriteString("\n")
	}
	b.WriteString("} as const satisfies Record<string, PLRule>;\n")
	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", out, err)
	}
	fmt.Println("wrote", out, "—", len(rules.Polish2026), "rules")
	return nil
}

// tsString single-quotes a string, escaping any embedded single quotes or
// backslashes. Matches prettier's default config so the generated file
// stays drift-free against the formatter.
func tsString(s string) string {
	escaped := strings.ReplaceAll(s, `\`, `\\`)
	escaped = strings.ReplaceAll(escaped, `'`, `\'`)
	return "'" + escaped + "'"
}

// outputPath finds the repo's src/lib/utils dir relative to this command,
// independent of the caller's working dir. Walks up from the executable's
// known location (we're under backend-go/cmd/gen-rules) to the repo root.
func outputPath() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	// backend-go is one level below repo root.
	for cur := wd; cur != "/"; cur = filepath.Dir(cur) {
		candidate := filepath.Join(cur, "src", "lib", "utils")
		if info, err := os.Stat(candidate); err == nil && info.IsDir() {
			return filepath.Join(candidate, "pl_rules.generated.ts"), nil
		}
	}
	return "", fmt.Errorf("could not locate src/lib/utils from %s", wd)
}
